name: 'Changelog action'
description: '当pr提交时校验提交信息，当pr合并后更加commit信息自动更新version和changelog'
author: 'Thomas'
branding:
  icon: 'git-branch'
  color: 'green'
inputs:
  githubToken:
    description: 'GitHub token'
    required: true
  issuesUrl:
    description: 'Tapd group url or issues page url'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
